version: '3.8'
services:
  mainserver:
    build: ./Server/MainServer
    container_name: "mainserver"
    ports:
      - 5000:5000
  authserver:
    build: ./Server/AuthServer
    container_name: "authserver"
    ports:
      - 5001:5001
  frontend:
    build: ./Client/clientui
    container_name: "frontendnctv1"
    ports:
      - 3000:3000
